### ISSUE TITLE
Category.txt, train_videofolder.txt, val_videofolder.txt

### ISSUE THREAD

**Issue by REDAMOUMEN** [okankop/MFF-pytorch#6] opened 2019-04-25 20:25 UTC
Hi your work is great, but there is a problem with some missing files, category.txt train_videofolder.txt and val_videofolder.txt are missing, are they empty so I should just create them if no please can you add them in the readme

**Comment by okankop** [comment] 2019-04-25 22:18
Hi, hapy to hear you like the work :) You need to use  process_dataset.py script to create these files. It is explained in the dataset preparation section in the Readme.

**Comment by Omenranr** [comment] 2019-04-26 11:09
Hello, I'm a friend of REDAMOUMEN and we have "hand gesture recognition" as a first year final project. Thank you for responding us quickly. We are lacking processing ressources so we are very gratefull that you published this work, this will help us get inspired & develop our skills. Also get good marks 😆.

**Comment by okankop** [comment] 2019-04-26 12:29
Unfortunately, there is no such a file that you can directly run the pretrained models on your data. However, it would be very similar to this: "https://github.com/metalbubble/TRN-pytorch/blob/master/test_video.py" 
With very little modification, you can make it working :+1:

**Comment by Omenranr** [comment] 2019-04-26 14:59
Ok, thank you for your help

**Comment by okankop** [comment] 2019-04-26 18:02
I believe, the issue is cleared out. I am closing the issue!

**Closed by okankop** 2019-04-26 18:02 UTC

**Comment by chenyuqing** [comment] 2019-06-23 13:20
@Omenranr @REDAMOUMEN Can you help me ? I am in trouble with dealing with dataset. For the preparation part. Thanks.

**Comment by Omenranr** [comment] 2019-06-26 14:22
@chenyuqing what problems are you facing ?
